services:
  db:
    container_name: db
    image: postgres:14.4-alpine  
    volumes:    
      - db:/var/lib/postgresql/data  
    env_file:    
      - .env
    networks:
      - shop_network

  shop_app:  
    container_name: shop_app  
    build:
      context: .
    depends_on:    
      - db  
    volumes:    
      - static:/static
      - media:/media  
    ports:    
      - 8000:8000
    env_file:    
      - .env
    networks:
      - shop_network

  redis:
    container_name : redis
    image: redis:7.0.3-alpine
    networks:
      - shop_network

  celery:
    container_name: celery
    build: .
    working_dir: /app
    command: ["celery", "-A", "core", "beat", "-l", "info"]
    volumes:
      - static:/static
      - media:/media  
    depends_on:
      - db
      - redis
    env_file:    
      - .env
    networks:
      - shop_network

  worker:
    container_name: worker
    build: .
    working_dir: /app
    command: ["celery", "-A", "core", "worker", "-l", "info"]
    volumes:
      - static:/static
      - media:/media  
    depends_on:
      - db
      - redis
    env_file:    
      - .env
    networks:
      - shop_network

  
  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - shop_app
    networks:
      - shop_network
  
networks:
    shop_network:
        driver: bridge

volumes:
  db:
  static:
  media: